# Use postgres/example user/password credentials

services:
  wallet:
    build: .
    ports:
      - 5000:5000
    container_name: wallet
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - pgdb
    # command: 


  pgdb:
    image: postgres
    restart: always
    shm_size: 128mb
    ports: 
      - 5432:5432
    container_name: pgdb
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
    



